In [2]:
from random import randint
import numpy as np
import matplotlib.pyplot as plt

!pip install qutip
from qutip import *

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.8/31.8 MB 40.4 MB/s eta 0:00:00


In [ ]:
print("hello world")

hello world


# Vectors and Matrices

To create vectors and matrices in python, we can use the array function in numpy.  To create the "0" vector, we would define:

In [3]:
zero = np.array([1,0])
print(zero)

[1 0]


Now you try defining the "1" vector using the same method as above:

In [8]:
#Write your code here
one = np.array([0,1])

We can also define our classical gates in this same method.  To create a 2x2 matrix, we use the following:

In [9]:
I = np.array([[1,0],[0,1]])
print(I)

[[1 0]
 [0 1]]


Now you try defining the NOT gate matrix using the same method as above:

In [10]:
#Write your code here
NOT = np.array([[0,1],[1,0]])

Can you use that same method to define the CNOT and SWAP gate matrices?

In [11]:
#Define CNOT here:
CNOT = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
print(CNOT)
#Define SWAP here:
SWAP = np.array([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]])
print(SWAP)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]


We can calculate the result of a single bit circuit that starts as a "0" and goes through a NOT gate by using a "dot product":

In [13]:
np.dot(NOT,zero)

array([0, 1])

We can calculate the result of a two-bit circuit that starts as |00> where the top (right) bit goes through a NOT gate and the bottom (left) bit doesn't do anything by using a Kronecker product.  First, we'll figure out what the vector is for the starting |00> state:

In [17]:
np.kron(zero,zero)

array([1, 0, 0, 0])

Then, we'll figure out what the Kronecker product is of the NOT gate on a top bit and the I gate on the bottom bit:

In [16]:
np.kron(I,NOT)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

Then, we can apply this gate to the initial |00> state:

In [18]:
np.dot(np.kron(I,NOT),np.kron(zero,zero))

array([0, 1, 0, 0])

Now what if we follow those operations with a SWAP gate performed between the two bits?

In [23]:
np.dot(SWAP,np.dot(np.kron(I,NOT),np.kron(zero,zero)))

array([0, 0, 1, 0])

Guess what?  There are even easier ways to do this!